version: '3.3'

services:
   wordpress:
     depends_on:
       - db
       - memcached
     image: docker.io/bitpoke/wordpress-runtime:bedrock
     volumes:
       - ./:/app
     ports:
       - "8080:8080"
     restart: always
     environment:
       DB_HOST: db:3306
       DB_USER: wordpress
       DB_PASSWORD: not-so-secure
       DB_NAME: wordpress
       MEMCACHED_HOST: memcached:11211
       WP_HOME: http://localhost:8080
       WP_SITEURL: http://localhost:8080/wp
       WP_ENV: development

   db:
     image: percona:5.7
     volumes:
       - db_data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: not-so-secure
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: not-so-secure

   memcached:
     image: memcached:1.5

volumes:
    db_data: {}
